### ISSUE TITLE
[Feature Request]: Unify all docker files

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#1286]
### Is your feature request related to a problem? Please describe.

Currently there are docker files in `samples/docker` and `.devcontainer`.

The former allows flexibility to specify many general Dockerfile s but the latter makes it easy to use DockerFile with vscode and Codespaces.

But because we now have two directories with Dockerfiles, as a user, now I need to decide which ones to use. And especially how to use the files in `samples` with vscode.

### Describe the solution you'd like

We need to figure out if its possible to 

- All docker files in a single place (e.g., .devcontainer)
- Have the docker files be compatible with both vscode, Codespaces, and other dev environments that do not use these

### Additional context

Example of diverging solutions:
#1275 #1241 
```[tasklist]
### Tasks
- [x] Review and Merge #1241
- [x] Move additional docker files from samples to .devcontainer with their own subdir
- [ ] https://github.com/microsoft/autogen/issues/1332
- [x] Double check which setups should be in Dockerfile vs devcontainer.json
- [x] Update website/docs/Contribute.md to remove redundant documentation and point to new
- [ ] Merge necessary proposal from #1275
- [ ] Update studio readme to point to studio dev container
```

**Comment by r3d91ll** [comment]
> I suggest the following solution:
> 
> create subdir for each dockerfile in .devcontainer. This way the docker files will be compatible with both Codespaces and non-codespaces environment while minimizing duplicate locations of docker files. @r3d91ll
> 
> See #1241 for an example (modulo the vscode customizations)

Nice work. See my pull  #1275 for the latest versions of the Dockerfile.full and Dockerfile.base. Aside from those two files, there was only a minor update to the Dockerfiles.md documentation with that pull. However, we will probably want to update the contribute and installation webpages to account for your .devcontainer setup.

**Comment by gagb** [comment]
> > I suggest the following solution:
> > create subdir for each dockerfile in .devcontainer. This way the docker files will be compatible with both Codespaces and non-codespaces environment while minimizing duplicate locations of docker files. @r3d91ll
> > See #1241 for an example (modulo the vscode customizations)
> 
> Nice work. See my pull #1275 for the latest versions of the Dockerfile.full and Dockerfile.base. Aside from those two files, there was only a minor update to the Dockerfiles.md documentation with that pull. However, we may want to update the contribute and installation webpages to account for your .devcontainer setup. If this is good for you, then I'll cancel my pull request in lieu of yours.

Thank you for the kind words @r3d91ll! Appreciate the collaboration on this!
I am making a new PR and will report back asap.

**Comment by qingyun-wu** [comment]
@gagb @r3d91ll Very nice! The plan looks good to me!
