### ISSUE TITLE
[Bug]: OpenAIWrapper import not working.

### ISSUE THREAD

**Issue by AkashKulkarni4444** [microsoft/autogen#1526]
## OpenAIWrapper not working
when using pyautogen v0.2.9
it can not use conversible_agent.py
this is because it results in OpenAIWrapper not found.

## Similar to 

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```
#1498 

### Steps to reproduce

Use pyautogen to create a conversibleAgent or any of it's sub classes.
Then it will cause this issue.

### Expected Behavior

Expected behaviour is that pyautogen should work properly and not cause any issues. 

### Logs
Process SpawnProcess-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
target(sockets=sockets)
File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 62, in run
return asyncio.run(self.serve(sockets=sockets))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
config.load()
File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 458, in load
self.loaded_app = import_from_string(self.app)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
module = importlib.import_module(module_str)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1204, in _gcd_import
File "", line 1176, in _find_and_load
File "", line 1147, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "/testApp/main.py", line 3, in
from chatBot import main as chatBotMain
File "/testApp/chatBot/main.py", line 17, in
import autogen.agentchat as autogenAgent
File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/init.py", line 2, in
from .assistant_agent import AssistantAgent
File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/assistant_agent.py", line 3, in
from .conversable_agent import ConversableAgent
File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 11, in
from .. import OpenAIWrapper
ImportError: cannot import name 'OpenAIWrapper' from 'autogen' (/usr/local/lib/python3.11/site-packages/autogen/init.py)

### Additional Information

pyautogen version : 0.2.9
python 3.11
os: windows 11
os: linux
(I tested on both)
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/autogen/issues/1498
- [ ] You only have to change the import statement. In conversable_agent.py instead of  ' from .. import OpenAIWrapper ' there should be ' from ..oai.client import OpenAIWrapper '
```

**Comment by ekzhu** [comment]
> ImportError: cannot import name 'OpenAIWrapper' from 'autogen' (/usr/local/lib/python3.11/site-packages/autogen/init.py)

The path doesn’t look right. Can you double check you have the right package installed? You can take a look at our project directories we don’t have this file.

**Comment by AkashKulkarni4444** [comment]
> > ImportError: cannot import name 'OpenAIWrapper' from 'autogen' (/usr/local/lib/python3.11/site-packages/autogen/init.py)
> 
> The path doesn’t look right. Can you double check you have the right package installed? You can take a look at our project directories we don’t have this file.

Yes you are correct .There is no such file in my local directory as well.
But there is one with the name \_\_init_\_\.py at the same place.

>File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 11, in
>from .. import OpenAIWrapper

This is the issue in line 11 of conversable_agent.py.

To solve this issue we just have to change import statement to 
from ..oai.client import OpenAIWrapper

I can do the changes in local directory to solve it . 
But I want to know if it is working for others .  As mentioned in #1498 . 
I think if it is a persistent issue then it should be resolved.

**Comment by ekzhu** [comment]
Thanks! I think this is a bug. Can you submit a PR to address this? Thanks for spotting!

**Comment by sonichi** [comment]
This problem doesn't occur for me. Could you try uninstall autogen and install pyautogen?

**Comment by ekzhu** [comment]
This problem happens when installing `pyautogen` from the cloned repo. i.e., `pip install -e .`. It doesn't happen if installing it from Pypi.

**Comment by ekzhu** [comment]
Okay. From comment on the other thread by @sonichi. At least I know the reason it happens for me is because I have a directory `autogen` in the path when I ran the import command. 

@AkashKulkarni4444  can you check if uninstalling `autogen` and install `pyautogen` work for you?

**Comment by AkashKulkarni4444** [comment]
> Okay. From comment on the other thread by @sonichi. At least I know the reason it happens for me is because I have a directory `autogen` in the path when I ran the import command.
> 
> @AkashKulkarni4444 can you check if uninstalling `autogen` and install `pyautogen` work for you?

I tried it once previously . It didn't work . 
I will try it again and update.

**Comment by AkashKulkarni4444** [comment]
> Okay. From comment on the other thread by @sonichi. At least I know the reason it happens for me is because I have a directory `autogen` in the path when I ran the import command.
> 
> @AkashKulkarni4444 can you check if uninstalling `autogen` and install `pyautogen` work for you?

1st I uninstalled autogen but not pyautogen .
Then it didn't work.
Then I uninstalled pyautogen.
Then I installed pyautogen again and it didn't cause the original error.

**Comment by ekzhu** [comment]
Thanks for the update. Would you like to add an FAQ entry about this? I myself was confused initially so I think many people would benefit from this.

**Comment by AkashKulkarni4444** [comment]
I think we should still update the import statement so that it is compatible with all the above cases.

**Comment by ekzhu** [comment]
@AkashKulkarni4444 could you open a PR for this change?

**Comment by AkashKulkarni4444** [comment]
> @AkashKulkarni4444 could you open a PR for this change?

@ekzhu  I just did .
