### ISSUE TITLE
[Core] Roadmap for handling context overflow

### ISSUE THREAD

**Issue by kevin666aa** [microsoft/autogen#156]
## Any help is appreciated!
Thit task demands a considerable amount of effort. If you have insights, suggestions, or can contribute in any way, your help would be immensely valued.

## Problem Description
(Continue from #9) Current LLM have limited context size / token limit (gpt3.5turbo: 4096, gpt4 8192, etc). Although the current max_token limit from OpenAI is sufficient for many tasks, the token limit will be always exceeded with the conversation running. autogen.Completion will raise this InvalidRequestError that indicates the context size is exceeded since autogen doesn’t have a way to handle long context sizes.

## Potential Methods
1. Compression: we can utilize LLMs to compress previous messages to reduce context size.
2. Retrieve related history messages: we can retrieve the most related messages based on the latest message.
3. Truncation: a simple way is keep the recent k messages and truncate all previous messages. We can also implement some truncation mechanisms, such as remove failed code executions.
4. A mixture of methods above.

## Some References
- https://community.openai.com/t/when-conversation-grows-larger-did-chatgpt-include-all-of-the-conversation-context-for-every-chat/121876/7
- https://ai.stackexchange.com/questions/38150/how-does-chatgpt-retain-the-context-of-previous-questions
- From @juanmacuevas: [MemWalker processed long context intro a tree of summaries](https://www.marktechpost.com/2023/10/13/researchers-from-princeton-and-meta-ai-introduce-memwalker-a-new-method-that-first-processes-the-long-context-into-a-tree-of-summary-nodes/) and [link to the paper](https://arxiv.org/abs/2310.05029) 
- [LongLLMLingua](https://arxiv.org/abs/2310.06839): local model for compression. 
- From @MrXandbadas: [MemGPT supporting Autogen Agent discussion]( https://github.com/cpacker/MemGPT/discussions/65#discussioncomment-7344551)

```[tasklist]
### Compression & Truncation
- [ ] https://github.com/microsoft/autogen/pull/131
- [ ] https://github.com/microsoft/autogen/pull/421
- [ ] https://github.com/microsoft/autogen/pull/443
- [ ] Allow async compression
- [ ] https://github.com/microsoft/autogen/pull/497
- [ ] https://github.com/microsoft/autogen/issues/685
```
```[tasklist]
### Retrieval
- [ ] Explore memGPT agent
```

**Comment by kevin666aa** [comment]
```[tasklist]
### Compression
- [ ] https://github.com/microsoft/autogen/pull/131
- [ ] Allow async compression
- [ ] Compression in GroupChat
- [ ] testing and improvement on `token_count_utils.py `
```

**Comment by kevin666aa** [comment]
```[tasklist]
### Compression
- [ ] https://github.com/microsoft/autogen/pull/131
- [ ] Allow async compression
- [ ] Compression in GroupChat
- [ ] testing and improvement on `token_count_utils.py `
```

**Comment by OrderAndCh4oS** [comment]
Probably a slight tangent, but I'm finding error stack traces to a major culprit of context overflow

**Comment by kazunator** [comment]
Would using something like Llama Index help?

**Comment by kazunator** [comment]
could this work? https://memgpt.ai/

**Comment by juanmacuevas** [comment]
[MemWalker, addresses challenges in processing long text and conversation contexts](https://medium.com/@multiplatform.ai/memwalker-developed-by-princeton-and-meta-ai-addresses-challenges-in-processing-long-text-and-50a0e1e80045)
Could this approach be applied for autogen? [link to the paper](https://arxiv.org/abs/2310.05029)

**Comment by sonichi** [comment]
@Hacker0912 Are you interested in this topic?

**Comment by qidanrui** [comment]
AutoGen is a great project! I'm very interested in how do you solve the context overflow. 
When I was using AutoGen, sometimes I meet this situation:
![捕获](https://github.com/microsoft/autogen/assets/10005367/6875785d-497f-4ddb-abbb-43d1b486ad41)
Do you have any possible solution now? Thanks!

**Comment by kevin666aa** [comment]
> AutoGen is a great project! I'm very interested in how do you solve the context overflow. When I was using AutoGen, sometimes I meet this situation: ![捕获](https://user-images.githubusercontent.com/10005367/276914508-6875785d-497f-4ddb-abbb-43d1b486ad41.PNG) Do you have any possible solution now? Thanks! @kevin666aa

Here is a experimental PR for compression: #131 . It would be great if you can check it out and test it!

Just found a potential good solution for compression and I will look into this: https://arxiv.org/abs/2310.06839

**Comment by qidanrui** [comment]
Thanks for sharing! @kevin666aa I'm so interested in the AutoGen project! 
I have two other more general questions: 1. what is the difference between AutoGen and ChatArena? 2. Can we customize our own tool/agent except python code writing like what we can do in LangChain?

**Comment by aaronstevenson408** [comment]
i also am having issue with using a mistral model , using textgen webui as the api host

**Comment by MrXandbadas** [comment]
> could this work? https://memgpt.ai/

https://github.com/cpacker/MemGPT/discussions/65#discussioncomment-7344551

**Comment by PriNova** [comment]
I suggest starting with the simplest implementations without external dependencies first and later building on these.
This means to use truncation so that the history has a sliding window set by users if custom models will be used.

Later on, the user can switch between different implementations how to handle context window through truncation, vector embeddings DB or MemGPT.

**Comment by Jepse** [comment]
is anyone trying to implement this onto gpt4All([https://gpt4all.io])? or are open source models just not "intelligent" enough yet?

**Comment by kevin666aa** [comment]
Hello, @MrXandbadas Thanks for the heads up! It's great to have a memGPT agent in AutoGen. It requires much effort to add memgpt, but it seems that we can work with people from memGPT to make it happen. I guess the first step would be to make memgpt a built-in agent in AutoGen. Then we can think about how users can switch with different options for context overflow.

@PriNova Thanks for the advice! Your suggestion of truncating history is brought up here #195. 
I am making a PR to add a compression agent for the user to choose here #131.
There are two parts to this PR: 
1. A implementation where user can switch between two modes at a pre-set token limit: 
`TERMINATE`: terminate the process before RateLimitError is raised; "COMPRESS": call a compression agent to compress previous messages.
2. A compression agent that does compression.

From the first part, it would be easy to add different ways to handle context later.
The compression agent is experimental but serves as a choice for now.


Please take a look at it if you are interested! @PriNova @MrXandbadas

**Comment by sonichi** [comment]
Sounds good, except "the first step would be to make memgpt a built-in agent in AutoGen." Before we make it a built-in agent, it'll be helpful to demonstrate one good use case of memgpt-based agent in autogen.

**Comment by JonMike12341234** [comment]
I must be totally misunderstanding the request for "one good use case".  Would this approach not give AutoGen Agents near limitless long term memory storage?

**Comment by sonichi** [comment]
Just suggesting doing it step by step. Test-driven development.

**Comment by MrXandbadas** [comment]
> Just suggesting doing it step by step. Test-driven development.

I completely agree. Testing it in an more robust setup would garner more fruitful insight as to if it was going to be beneficial for the system or just a hinderance in the continual prompt generation that allows these agents to function so flawlessly.

**Comment by ddwinhzy** [comment]
I think it's gonna be a great start.

**Comment by SDcodehub** [comment]
I am interested in this topic, is anyone working on this? I can help can work together with others

**Comment by kevin666aa** [comment]
> I am interested in this topic, is anyone working on this? I can help can work together with others

Hello @SDcodehub, thanks for your interest! Currently I am working on adding a compressible agent #443. It could be used as an interface for different types of compression and truncations. 
I think it is a good start pointing to know what we are doing.
I am starting a draft for compressible groupchat in #497. 
The next step will be to allow async management of history.

On the other hand, it is also possible to utilize existing framework like memGPT. memGPT is actively supporting autogen agents. As @sonichi pointed out, we need to "demonstrate one good use case of memgpt-based agent in autogen". It is not hard to add a memGPT agent, but how to modify it to serve as a group memory requires more effort and thinking.

**Comment by GregorD1A1** [comment]
Hey guys!

The lack of possibility to see exact prompt which agent gets to a context and lack of ability of managing agent's contexts are the main problems of autogen in my opinion. Main reason for it is not even overflow of context window - the main reasons is the LLMs working much worse when had too long context with a lot of useless noise, and also generate unnecesary costs.

Maybe you remember, lack of input prompt visibility was big problem with Langchain, until they did a Langsmith. With autogen we have same problem again. In my opinion, we can't talk about any serious AI development if we can't see and edit input prompt of LLMs.

What do you think about it? Is such features of editing context (as summarizing or removing old messages) will be available in near future? Maybe there are already solutions exist I don't know about? 

Cheers!

**Comment by sonichi** [comment]
I'm quite excited at #1091 by @rickyloynd-microsoft. It makes the teachability a composable capability to any conversable agent. More generally, the same mechanism may be used for solving other longstanding issues like long context handling and allowing other interesting capabilities to be defined. I like the extensibility and the composability of this approach. Reviews are welcome.
cc @kevin666aa

**Comment by sgjohnson1981** [comment]
> I'm quite excited at #1091 by @rickyloynd-microsoft. It makes the teachability a composable capability to any conversable agent. More generally, the same mechanism may be used for solving other longstanding issues like long context handling and allowing other interesting capabilities to be defined. I like the extensibility and the composability of this approach. Reviews are welcome. cc @kevin666aa

So does @rickyloynd-microsoft 's PR add a feature that eliminates the need for MemGPT or other context length solutions? I can't tell from "...mechanism may be used..." Is this mechanism used now for context length, or will that be implemented later?

**Comment by rickyloynd-microsoft** [comment]
> > I'm quite excited at #1091 by @rickyloynd-microsoft. It makes the teachability a composable capability to any conversable agent. More generally, the same mechanism may be used for solving other longstanding issues like long context handling and allowing other interesting capabilities to be defined. I like the extensibility and the composability of this approach. Reviews are welcome. cc @kevin666aa
> 
> @sonichi So does @rickyloynd-microsoft 's PR add a feature that eliminates the need for MemGPT or other context length solutions? I can't tell from "...mechanism may be used..." Is this mechanism used now for context length, or will that be implemented later?

Teachability is just one capability added through this new mechanism, and teachability is not designed to compress context or memorize general things like MemGPT. But other capabilities (like MemGPT or other ways of handling long context) could be added through this general capability-addition mechanism.

**Comment by ekzhu** [comment]
Shall we close this issue as several recent PRs related to long context handling have merged. @kevin666aa

**Comment by kevin666aa** [comment]
Yes, thanks!

**Comment by jinggong1995** [comment]
Hi, I'm working on conversable agent flow with autogen. and really wants to know the status of handling context window length and truncate chat history. 

I read the above conversation and have a few questions?
1. Is the status already completed and released? 
2. Is there any docs or paper from autogen explaining how this is being handled specifically?

It would be really helpful if you can answer the question!

**Comment by ekzhu** [comment]
@JingPush current we use this: https://microsoft.github.io/autogen/docs/topics/long_contexts

**Comment by reski-rukmantiyo** [comment]
> [@JingPush](https://github.com/JingPush) current we use this: https://microsoft.github.io/autogen/docs/topics/long_contexts

it's 404 now. how to solve this?
