### ISSUE TITLE
[Roadmap] RAG

### ISSUE THREAD

**Issue by thinkall** [microsoft/autogen#1657]
## Why RAG
Retrieval-Augmented Generation (RAG) is a technique that enhances the capabilities of LLMs by incorporating a retrieval mechanism into the generative process. This approach allows the model to leverage a vast amount of relevant information from a pre-existing knowledge base, which can significantly improve the quality and accuracy of its generated responses. Thus, for agents chat, incorporating a RAG agent offers several compelling advantages that can significantly enhance the performance and utility of your agent system.

## RAG in AutoGen
AutoGen has provided `RetrieveUserProxyAgent` and  `RetrieveAssistantAgent` for performing RetrieveChat in Aug, 2023 and announced it in [blog](https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat) in Oct, 2023. Given a set of documents, the Retrieval-augmented User Proxy first automatically processes documents—splits, chunks, and stores them in a vector database. Then for a given user input, it retrieves relevant chunks as context and sends it to the Retrieval-augmented Assistant, which uses LLM to generate code or text to answer questions. Agents converse until they find a satisfactory answer.

![retrievechat-arch-old](https://microsoft.github.io/autogen/assets/images/retrievechat-arch-959e180405c99ceb3da88a441c02f45e.png)

As both AutoGen and RAG are evolving very fast, we find that many users are asking for supports on customized vector databases, incremental document ingesting, customized retrieve/re-ranking algorithms, customized RAG pattern/workflow, etc. We've adjusted some of the issues and feature requests, such as we've added `QdrantRetrieveUserProxyAgent` for using qdrant as the vector db;  we've integrated UNSTRUCTURED to support many unstructed documents. However, there are many more to do.

## Our Plan
In order to better support RAG in AutoGen, we plan to refactor the existing RetrieveChat agents. The goals includes:

### Primary goals
- [ ] Support launching RAG with one agent instead of two
- [x] Support customizing vector databases with a parameter instead of extending agent class
- [ ] Support RAG in AutoGen Studio
- [ ] Support leveraging 3rd-party OSS tools
- [ ] Make RAG a capability for any conversable agent
- [ ] Support RAG as a tool like in OpenAI Assistant
- [x] Make vector db dependency optional 
- [ ] the chat interface of the RAG agent is the same as any other conversable agent

### Optional goals
- [ ] Support async functions
- [ ] Support benchmarks
- [ ] Support evaluation

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/autogen/issues/1469
- [ ] https://github.com/microsoft/autogen/issues/1387
- [ ] https://github.com/microsoft/autogen/issues/1440
- [ ] https://github.com/microsoft/autogen/pull/1661
- [ ] https://github.com/microsoft/autogen/issues/1726
- [ ] https://github.com/microsoft/autogen/issues/1047
- [ ] https://github.com/microsoft/autogen/discussions/484
- [ ] Automatically decide whether RAG is needed
- [ ] Add a score threshold for retriever
- [ ] https://github.com/microsoft/autogen/pull/2263
- [ ] https://github.com/microsoft/autogen/pull/2271
- [ ] https://github.com/microsoft/autogen/pull/2289
- [ ] https://github.com/microsoft/autogen/issues/1844
- [ ] https://github.com/microsoft/autogen/issues/531
- [ ] https://github.com/microsoft/autogen/issues/725
- [ ] https://github.com/microsoft/autogen/issues/859
- [ ] https://github.com/microsoft/autogen/issues/1723
- [ ] https://github.com/microsoft/autogen/issues/1282
- [ ] https://github.com/microsoft/autogen/issues/1261
- [ ] https://github.com/microsoft/autogen/pull/2313
- [ ] Add documentation to user guide
- [ ] Delete files from a collection?
- [ ] Add better code parser
- [ ] https://github.com/microsoft/autogen/pull/2942
- [ ] https://github.com/microsoft/autogen/pull/2881
- [ ] https://github.com/microsoft/autogen/pull/2883
- [ ] https://github.com/microsoft/autogen/pull/2865
- [ ] https://github.com/microsoft/autogen/pull/2566
- [ ] https://github.com/microsoft/autogen/pull/2455
- [ ] https://github.com/microsoft/autogen/pull/2259
- [ ] https://github.com/microsoft/autogen/pull/2248
- [ ] https://github.com/microsoft/autogen/issues/3046
- [ ] https://github.com/microsoft/autogen/pull/3035
- [ ] https://github.com/microsoft/autogen/pull/3000
- [ ] https://github.com/microsoft/autogen/pull/3140
- [ ] Update RAG blog, the custom vectordb section
- [ ] https://github.com/microsoft/autogen/pull/3320
- [ ] https://github.com/microsoft/autogen/pull/3388
- [ ] https://github.com/microsoft/autogen/issues/3119
```

**Comment by Knucklessg1** [comment]
Hello, I was wondering if there was support coming for pgvector, if not I would be happy to contribute.

**Comment by julianakiseleva** [comment]
@thinkall

**Comment by thinkall** [comment]
> Hello, I was wondering if there was support coming for pgvector, if not I would be happy to contribute.

Hi @Knucklessg1 , contribution is welcome, thank you for your interest!

**Comment by WaelKarkoub** [comment]
Hi @thinkall, would this PR, https://github.com/microsoft/autogen/pull/2046, help out with `Automatically decide whether RAG is needed`?

I was thinking if the agent adds a tag like `<rag context="some context">` in the message, we can intercept that by one of the hooks or even a reply, and then perform some rag operations

**Comment by thinkall** [comment]
> Hi @thinkall, would this PR, #2046, help out with `Automatically decide whether RAG is needed`?
> 
> I was thinking if the agent adds a tag like `<rag context="some context">` in the message, we can intercept that by one of the hooks or even a reply, and then perform some rag operations

Thank you @WaelKarkoub , interesting idea! Would adding <rag context="some context"> mean RAG is already performed?

**Comment by WaelKarkoub** [comment]
@thinkall we could define what that tag means by adding attributes (e.g. `<rag context=`some context` task=`search`> could mean it needs to look through some databases) I'm not fully familiar with how rag works, but that tag system should be general enough for multiple use cases.

**Comment by ChristianWeyer** [comment]
Great initiative @thinkall.
How much are you thinking of reusing what has already been built and proven in other frameworks, like LangChain?

**Comment by thinkall** [comment]
> Great initiative @thinkall. How much are you thinking of reusing what has already been built and proven in other frameworks, like LangChain?

Thank you @ChristianWeyer , I hope to support as many established features in the OSS as possible. So we're carefully thinking of the new design of the rag feature in AutoGen. Would you like to share your thoughts?

**Comment by ChristianWeyer** [comment]
> > Great initiative @thinkall. How much are you thinking of reusing what has already been built and proven in other frameworks, like LangChain?
> 
> Thank you @ChristianWeyer , I hope to support as many established features in the OSS as possible. So we're carefully thinking of the new design of the rag feature in AutoGen. Would you like to share your thoughts?

One thing is that there are so many connector & retriever implementations in LangChain, that it would not make sense to reinvent the wheel and trying to keep up. Same goes for embedding support.

**Comment by dsalas-crogl** [comment]
@thinkall Will the upcoming RAG update still require using `message_generator` in groupchat scenarios? It's my understanding that currently, the RAG agent has to initiate chat and `message_generator` has to be used, which results in all initial prompt messages being sent through retrieve_docs in RetrieveUserProxyAgent.

**Comment by ChristianWeyer** [comment]
> > > > Great initiative @thinkall. How much are you thinking of reusing what has already been built and proven in other frameworks, like LangChain?
> > > 
> > > 
> > > Thank you @ChristianWeyer , I hope to support as many established features in the OSS as possible. So we're carefully thinking of the new design of the rag feature in AutoGen. Would you like to share your thoughts?
> > 
> > 
> > One thing is that there are so many connector & retriever implementations in LangChain, that it would not make sense to reinvent the wheel and trying to keep up. Same goes for embedding support.
> 
> Agree!
> 
> Would you like to have a quick chat on this? It would be great to hear more from you!

Sure. I am cethewe in AG Discord.

**Comment by thinkall** [comment]
> > Hello, I was wondering if there was support coming for pgvector, if not I would be happy to contribute.
> 
> Hi @Knucklessg1 , contribution is welcome, thank you for your interest!

Hi @Knucklessg1 , are you in our Discord channel? Could we have a quick chat? Thanks.

**Comment by thinkall** [comment]
> @thinkall Will the upcoming RAG update still require using `message_generator` in groupchat scenarios? It's my understanding that currently, the RAG agent has to initiate chat and `message_generator` has to be used, which results in all initial prompt messages being sent through retrieve_docs in RetrieveUserProxyAgent.

Hi @dsalas-crogl , I'd like to remove the usage of `message_generator`, would that benefit your use case? Thanks.

**Comment by Knucklessg1** [comment]
> > > Hello, I was wondering if there was support coming for pgvector, if not I would be happy to contribute.
> > 
> > 
> > Hi @Knucklessg1 , contribution is welcome, thank you for your interest!
> 
> Hi @Knucklessg1 , are you in our Discord channel? Could we have a quick chat? Thanks.

Yes absolutely. I reached out on Discord.

**Comment by jamesliu** [comment]
@thinkall any flow diagram regarding the rag?

**Comment by thinkall** [comment]
> @thinkall any flow diagram regarding the rag?

Hi @jamesliu , there's one diagram [here](https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat/), you can find the workflow details in the Introduction section.

**Comment by Josephrp** [comment]
interesting roadmap , and i'm very happy with chromadb , looking forward to in memory vector store too , now. if anyone is interested it could be a good opportunity to collaborate and break down complex tasks .

i'll also consider creating + sharing an "advanced upsert" agent , which enriches the text chunks  to improve retrieval performance.

**Comment by raolak** [comment]
Does RAG usecases will be applicable only for documents or even for code 
Example 

- Existing code on which we need to run fix?  or
- new code which goes through incremental development

Usecase:
 - A system having multiple microservices which undergoes increment features or fixes. How does agent know about this knowledge? through RAG?
 - A new Microservices getting developer for given system, if I were to use Agents how existing knowledge can be fed to agents for better design and implementation?

**Comment by thinkall** [comment]
> Are RAG applications limited to document processing, or do they extend to code-related tasks as well? For instance:
> 
> * Existing code on which we need to run fix?  or
> * New codes (eg. new service) which goes through incremental development
> 
> Usecase:
> 
> * In a system comprised of numerous microservices that are regularly updated with new features or fixes, how can an agent acquire knowledge about these changes? Is RAG a viable method for this?
> * For the development of new microservices within an existing system, how can knowledge be transferred to agents to enhance the design and implementation process using RAG?

RAG can help if the documents are well organized. For pure code, currently, you can use 3rd party code chunk methods to help load the code into the vector dbs.

**Comment by ekzhu** [comment]
Let's also add documentation task to the roadmap? We should have a rag category under https://microsoft.github.io/autogen/docs/topics

**Comment by ChristianWeyer** [comment]
Do we also have a task on the roadmap for using custom embeddings? This is a very vital and important requirement for successful RAG.
Another would be to optionally use a re-ranking model to improve RAG results.

**Comment by thinkall** [comment]
> Do we also have a task on the roadmap for using custom embeddings? This is a very vital and important requirement for successful RAG. Another would be to use a re-ranking model optionally to improve RAG results. @thinkall

Custom embeddings are already supported and will also be supported in the new version.

Re-ranking may also be supported, but we may not implement the algorithms, instead we could support plugin different re-ranking models.

**Comment by maximedupre** [comment]
> > Are RAG applications limited to document processing, or do they extend to code-related tasks as well? For instance:
> > 
> > * Existing code on which we need to run fix?  or
> > * New codes (eg. new service) which goes through incremental development
> > 
> > Usecase:
> > 
> > * In a system comprised of numerous microservices that are regularly updated with new features or fixes, how can an agent acquire knowledge about these changes? Is RAG a viable method for this?
> > * For the development of new microservices within an existing system, how can knowledge be transferred to agents to enhance the design and implementation process using RAG?
> 
> RAG can help if the documents are well organized. For pure code, currently, you can use 3rd party code chunk methods to help load the code into the vector dbs.

@thinkall Is it possible for you to provide an example of a 3rd party code chunk method? I'm very interested in extending the knowledge of an agent to my whole codebase :)

**Comment by raolak** [comment]
I’ve got some thoughts on how we could use agents to automate code
generation

+1 for Maxime, it would be really helpful to include a section on code
chunking with examples to illustrate the working.

Now, when it comes to generating code, agents shouldn't just spit out code,
they should mimic the way engineers think and work in real life.
Here’s what I mean:

   - Start by clearly defining the requirements—think OKRs that cascade
   from key results down to epics and stories.
   - Set up milestones and break down tasks among the agents involved.
   - Have each agent carry out their tasks and check in regularly to ensure
   everything’s on track, with room for human oversight when needed.
   - Provide visibility of OKR, milestones and tasks visibility at one
   place. Make a planner central for agent and human collaboration and
   progress tracking.
   - Keep the agent's execution isolated (in a separate process). May be a
   distributed workflow where each node can host one or more agents. Workflow
   is orchestrated through central planner contributed by agents and humans

For the code workflow, we could see something like this:

   - Set up a new GitHub project with a clean, well-structured setup and
   isolated code (for new projects).
   - Handle resource creation, both on-premises and in the cloud.
   - Back it all up with a CI/CD system tailored for both on-premises and
   cloud environments.
   - Support incremental code commits through PR with CI/CD

These steps would be helpful both for rolling out new features or fixes to
existing projects and for starting fresh ones. I managed to get a mini
reference implementation of a distributed key-value store (80%) using
chatgpt(gpt4) and was able to build, test, and run the services locally
(screenshot attached). I was experimenting with autogen to reproduce the
steps that I have followed and see if I can achieve decent level autonomy
(I am sure it will take many iterations :) ). I am still learning and
experimenting. I will share my findings as I make progress.
[image: Screenshot 2024-04-13 at 10.37.18 AM.png]

Thanks for all the great work and support.

Regards
lnr

**Comment by cforce** [comment]
@raolak 

A solution for this has just been released
Checkout https://github.com/princeton-nlp/SWE-agent

**Comment by thinkall** [comment]
> @thinkall Is it possible for you to provide an example of a 3rd party code chunk method? I'm very interested in extending the knowledge of an agent to my whole codebase :)

Hi @maximedupre , please check out an example of using 3rd party chunk method here: https://microsoft.github.io/autogen/blog/2023/10/18/RetrieveChat/#customizing-text-split-function

**Comment by tianlinzx** [comment]
Any plan to integrate with GraphRAG ??

**Comment by wammar** [comment]
@thinkall @qingyun-wu 

Some of my team members recently started using AutoGen with RAG and are interested in contributing, but it is unclear what you're actively working on and what tasks do you need help with. It'd be great to collaborate if there's good alignment between this work stream and Holistic Intelligence for Global Good.

**Comment by thinkall** [comment]
> Any plan to integrate with GraphRAG ??

We're working on it. 
cc @randombet , @2152505

**Comment by thinkall** [comment]
> @thinkall @qingyun-wu
> 
> Some of my team members recently started using AutoGen with RAG and are interested in contributing, but it is unclear what you're actively working on and what tasks do you need help with. It'd be great to collaborate if there's good alignment between this work stream and Holistic Intelligence for Global Good.

Thank you very much, @wammar, for your feedbacks! The tasks list contains RAG related issues and PRs we're working on. You're very welcome to raise PRs for resolving existing issues or propose new features such as new vector dbs, new retrieve util functions (file parsing, chunking, etc.), or review PRs.

Any thoughts, suggestions, comments are very welcome.

**Comment by zhwuwuwu** [comment]
> > Any plan to integrate with GraphRAG ??有没有计划与 GraphRAG 集成 ？？
> 
> We're working on it. 我们正在努力。 cc [@randombet](https://github.com/randombet) ,  抄送[@2152505](https://github.com/2152505)

Is there any progress on it？

**Comment by devspacenine** [comment]
How will the RAG pattern change with the new v0.4 architecture?

**Comment by rysweet** [comment]
closing in favor of more specific feature issues in 0.4.x
