### ISSUE TITLE
[Roadmap] [.Net] Roadmap to official release

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/autogen#1704]
### Describe the issue

The preview-version AutoGen.Net is already available in GitHub package.

To proceed to official release (v1.0.0), there’re a few working items needs to be resolved
- graph-groupchat #1648 
- docker-based Code interpreter for dotnet and python
- Streaming middleware support #1656
- Message abstraction, semantic kernel integration #1647 #1676 
- distribute agent abstraction (‘IAgent’ and ‘IMessage’, etc) in another package #1676 

## Document updates
- Add document for middleware #1862 
- Add document for workflow and conditional transition #1862 

## Document improvements [#1922]
- [ ] Improve document for function call middleware
- [ ] Improve document for group chat

Also Cc @ekzhu @sonichi for feedback and review 
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/autogen/issues/48
```

**Comment by LittleLittleCloud** [comment]
@ekzhu The issues in this roadmap are all resolved, maybe we can mark this roadmap as completed?

**Comment by ekzhu** [comment]
> @ekzhu The issues in this roadmap are all resolved, maybe we can mark this roadmap as completed?

Yay!
