### ISSUE TITLE
Roadmap for releasing a new web application based on autogen.

### ISSUE THREAD

**Issue by pcdeadeasy** [microsoft/autogen#196]

**Comment by Rockets2TheMoon** [comment]
Very excited for this! How can I contribute?

**Comment by KenDingel** [comment]
^ Same here!

**Comment by pcdeadeasy** [comment]
Thanks for your interest. The goal is to release a research assistant that allows you to do q & a on papers, aggregate results, create visualizations/artifacts, skills that can be reused.
Tagging @sonichi @victordibia
@gagb @afourney

**Comment by binary-husky** [comment]
I working on implementing AutoGen in GPT-Academic:  https://github.com/binary-husky/gpt_academic/

**Comment by sonichi** [comment]
I know two options: register a callback function using `register_reply` or use web sockets. @victordibia do you have a better answer?

**Comment by binary-husky** [comment]
In https://github.com/microsoft/autogen/pull/322 , I remap callback by :

```
agent_handle._print_received_message = lambda a,b: self.gpt_academic_print_override(agent_kwargs, a, b)
if agent_kwargs['name'] == 'user_proxy':
    agent_handle.get_human_input = lambda a: self.gpt_academic_get_human_input(user_proxy, a)
    user_proxy = agent_handle
if agent_kwargs['name'] == 'assistant': assistant = agent_handle
```

**Comment by binary-husky** [comment]
> In #322 , I remap callback by :
> 
> ```
> agent_handle._print_received_message = lambda a,b: self.gpt_academic_print_override(agent_kwargs, a, b)
> if agent_kwargs['name'] == 'user_proxy':
>     agent_handle.get_human_input = lambda a: self.gpt_academic_get_human_input(user_proxy, a)
>     user_proxy = agent_handle
> if agent_kwargs['name'] == 'assistant': assistant = agent_handle
> ```

`register_reply` is a good idea, however, several flag variables are probably required inside autogen code.

**Comment by sonichi** [comment]
It looks to be on the right track. What flag variables are you referring to?

**Comment by ragyabraham** [comment]
Hey @sonichi @pcdeadeasy @binary-husky, we have just released a web app based on autogen. You can find the repo [here](https://github.com/rnadigital/agentcloud). It is still early days, but we intend to build out a lot of features to help accelerate uptake and also to help non-technical users get the most out of autogen

**Comment by ragyabraham** [comment]
Sure @pcdeadeasy so you're after an arch diagram to show how the messages are being passed from `agent-backend` to `webapp`?

**Comment by GoldenWind8** [comment]
Where can we make contributions and what tech stack is going to be used?

**Comment by sonichi** [comment]
@GoldenWind8 would you like to review #509 ?

**Comment by gagb** [comment]
New relevant PR: https://github.com/pcdeadeasy/autogen-oss/pull/2

**Comment by victordibia** [comment]
An initial commit on this has been made to the autogen repo in `/samples/apps/autogen-assistant` .

Some next steps 

```[tasklist]
### Requested Features
- [ ] Make agent selection persistent and based on db entries.
- [ ] Change subtitle to by Multi-Agents
- [ ] Save/export logs from interactions.
- [ ] Use function calling to register and execute functions instead of putting them in prompt
- [ ] Stream messages from agents to UI as they are generated
- [ ] Add other contributed agents: teachable agent, compressible agent, gptassistant agent
```

@gagb

**Comment by gagb** [comment]
Moving the task list to new issue here: https://github.com/microsoft/autogen/issues/737

**Comment by victordibia** [comment]
Closing this due to inactivity.

References

- [AutoGen studio](https://github.com/microsoft/autogen/tree/autogenstudio/samples/apps/autogen-studio) is the emerging reference example of using AutoGen with a web interface. 
- Roadmap for AutoGen Studio is here #737
