### ISSUE TITLE
[Roadmap] Complex workflows and composition made easier

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#2012]
### Describe the issue

> [!TIP]
> ## Want to get involved?
> We'd love it if you did! Please get in contact with the people assigned to this issue, or leave a comment. See general contributing advice [here](https://microsoft.github.io/autogen/docs/Contribute) too.

### What is the feature?

We want to make it easier to compose complex chats: nested chat, graph group chat, graph group chat with constraints, multi-step chat… and you can now create these complex chats in AutoGen Studio.

Please feel free to share your feedback and comments!  

```[tasklist]
### Tasks
- [x] Sequential chat: https://github.com/microsoft/autogen/pull/1402
- [x] Nested chat: https://github.com/microsoft/autogen/pull/1753
- [x] Group group chat: https://github.com/microsoft/autogen/pull/857
- [x] Group chat with custom speaker selection policy: https://github.com/microsoft/autogen/pull/1791
- [x] Finite State Machine: https://github.com/microsoft/autogen/pull/1622
- [x] Introducing StateFlow: https://github.com/microsoft/autogen/pull/1826
- [x] Supporting callable message in agent chats: https://github.com/microsoft/autogen/pull/1852
- [x] Further API enhancements idenfitified in PR1852: https://github.com/microsoft/autogen/pull/1852
- [ ] https://github.com/microsoft/autogen/issues/2014
- [ ] Realize the added supports in AutogGen Studio
- [ ] Enhance usability of complex workflow orchestration
- [ ] Comparative study with other alternatives
- [ ] Blogpost
- [ ] (Graph) Group chat with constraints, e.g., constrained message passing to a subset of agents
- [ ] https://github.com/microsoft/autogen/issues/2015
- [ ] https://github.com/microsoft/autogen/issues/2140
- [ ] Reimplement SocietyOfMind Agent with nested chat
- [ ] https://github.com/microsoft/autogen/issues/2457
```

**Comment by rysweet** [comment]
resolved in 0.4 arch
