### ISSUE TITLE
Better documentation of complex workflow

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#2015]
```[tasklist]
### Tasks
- [ ] better docstr for summary_args and carryover
- [ ] add a "topic" in website: https://microsoft.github.io/autogen/docs/topics
- [ ] https://github.com/microsoft/autogen/pull/2064
```

**Comment by ekzhu** [comment]
Shall we also add another task which is to add links from front page, tutorial, and readme to the relevant complex task pages?

**Comment by rysweet** [comment]
see 0.4 docs
