### ISSUE TITLE
support new openai package

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#203]
https://github.com/openai/openai-python/discussions/631

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/autogen/issues/384
- [ ] https://github.com/microsoft/autogen/issues/385
- [ ] https://github.com/microsoft/autogen/issues/386
- [ ] https://github.com/microsoft/autogen/issues/387
- [ ] https://github.com/microsoft/autogen/issues/388
- [x] remove openai.api_version
- [x] remove openai.api_type
- [x] support [aoai](https://github.com/openai/openai-python/blob/v1/examples/azure.py)
- [x] Response objects are now pydantic models and no longer conform to the dictionary shape.
- [x] headsup about dependency change
- [ ] https://github.com/microsoft/autogen/issues/402
- [ ] merge to main
- [ ] https://github.com/microsoft/autogen/issues/442
- [ ] https://github.com/microsoft/autogen/issues/450
- [ ] https://github.com/microsoft/autogen/issues/451
- [ ] https://github.com/microsoft/autogen/issues/476
```

**Comment by sonichi** [comment]
I'm about to get started on this issue. Suggestions and code reviews are welcome.
