### ISSUE TITLE
[Roadmap] CAP

### ISSUE THREAD

**Issue by rajan-chari** [microsoft/autogen#2088]
> [!TIP]
> ## Want to get involved?
> We'd love it if you did! Please get in contact with the people assigned to this issue, or leave a comment. See general contributing advice [here](https://microsoft.github.io/autogen/docs/Contribute) too.

## Description

CAP Roadmap
1) Integrating CAP into core AutoGen
2) Creating demos of capabilities
3) Creating useful components that integrates AutoGen with other tools (like teams)
4) Improve CAP (technical debt)

```[tasklist]
- [x] Search for registered agents
- [x] Remove Sleeps from Actor creation, ActorSender, ActorConnector in the CAP framework
- [ ] Add namespaces to DirectorySvc to facilitate several agent networks with only one publicly addressable agent
- [ ] Remote AutoGen Agents demo
- [ ] Long lived AutoGen agents demo
- [ ] Teams (C#) Agent that can work with pyautogen
- [ ] C++ Agent that can host llamacpp and work with pyautogen
```

**Comment by sonichi** [comment]
The description might be wrong.

**Comment by gagb** [comment]
@rajan-chari can you please update the description and roadmap task list for CAP?

**Comment by ChristianWeyer** [comment]
Hey all, so we have any kind of timeline when CAP would be fully implemented?
Thanks!

.cc @gagb @rajan-chari

**Comment by rysweet** [comment]
closing in favor of more specific issues.
