### ISSUE TITLE
[.Net][Feature Request]: Update Azure.AI.OpenAI package to 1.0.0-beta.15

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/autogen#2346]
### Is your feature request related to a problem? Please describe.

The `1.0.0-beta.15` Azure.AI.OpenAI supports new features like `json_mode` and `deterministic_output`

```[tasklist]
### Tasks
- [ ] Update Azure.AI.OpenAI to 1.0.0-beta.15
- [ ] Add example to show how to use json_mode in OpenAIAgent
- [ ] Update version number && publish a new release
```
