### ISSUE TITLE
[Roadmap] Persistence and state management

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#2358]
We want to be able to persist the state of a multi-agent workflow and restart from a given state. This is required for large-scale deployment of AutoGen workflows. The key steps are:

1. How to inject state (e.g., conversation history) into a multi-agent workflow so it starts from a given state. This functionality can also be used to implement in-context learning for individual agents, so they learn from a curated set of instructions and examples before participating in a workflow.
2. How to export the state of a multi-agent workflow. 

We start building (1) and (2) for individual class:

- single-agent
- two-agent chat
- sequential chats
- group chat, 

and then move on to think about a composed workflow of multiple conversation patterns. 

```[tasklist]
### Tasks
- [ ] GPTAssistantAgent add "thread_id" to its constructor to gain prior message histories. @jtrugman
- [ ] `initiate_chat` to add prior conversation histories for the two-agent chat.
- [ ] https://github.com/microsoft/autogen/issues/2359
- [ ] https://github.com/microsoft/autogen/issues/2671
```

**Comment by NikolayTV** [comment]
Hi! I have following use case:
In multi-agen conversation with human, there is an Agent named "collector" which collects info about the user to json from  conversation. That meta-information  I want to use sometimes, and "coordinator" will decide when to call it to context.

Is this feature about state management? I want to implement it for my project, and may be it will be nice to PR this to main repo too?

**Comment by randombet** [comment]
How could this support async chats?

**Comment by ekzhu** [comment]
Partially completed due to resumable group chat. We can open new issue if necessary.
