### ISSUE TITLE
[Feature Request]: Integrate more model calling to AutoGen through API

### ISSUE THREAD

**Issue by yiranwu0** [microsoft/autogen#2841]
### Is your feature request related to a problem? Please describe.

Besides OpenAI and Gemini Integration, there are existing other models that are available through API calling. It would be helpful if AutoGen could provide an uniform interface for calling different models.
Specifically, the following models could be added:
- Mistral: https://mistral.ai/technology/
- Claude: https://www.anthropic.com/api
- Various open-source models are supported by providers that allow easy usage through function calling. For example Deepinfra: https://deepinfra.com/. It is wrapped with OpenAI class, which is easy to implement.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/autogen/pull/2902
- [ ] https://github.com/microsoft/autogen/issues/2900
- [ ] #2892
- [ ] https://github.com/microsoft/autogen/pull/2916
- [ ] https://github.com/microsoft/autogen/pull/2931
- [ ] https://github.com/microsoft/autogen/pull/2919
```

**Comment by Hk669** [comment]
@marklysze as mentioned yesterday, can i know if you are working on the anthropic? ive seen the TogetherAI draft PR #2919. i can work on anthropic client if it is not implemented already. thanks

**Comment by marklysze** [comment]
> @marklysze as mentioned yesterday, can i know if you are working on the anthropic? ive seen the TogetherAI draft PR #2919. i can work on anthropic client if it is not implemented already. thanks

Hi @Hk669, thanks for checking, sorry it is the Together AI client I was working on. I'm not working on the Anthropic client but there is a notebook witt a sample Anthropic custom client class in the non-openai topic in documentation that could help with the new class. Happy to test if you can work on the class.

**Comment by Hk669** [comment]
> > @marklysze as mentioned yesterday, can i know if you are working on the anthropic? ive seen the TogetherAI draft PR #2919. i can work on anthropic client if it is not implemented already. thanks
> 
> Hi @Hk669, thanks for checking, sorry it is the Together AI client I was working on. I'm not working on the Anthropic client but there is a notebook witt a sample Anthropic custom client class in the non-openai topic in documentation that could help with the new class. Happy to test if you can work on the class. 

Sure, thanks for the clarification.

**Comment by Hk669** [comment]
@yiranwu0 , i believe we can close this issue.
