### ISSUE TITLE
[Feature Request]: Gemini API for .NET

### ISSUE THREAD

**Issue by hsm207** [microsoft/autogen#2851]
### Is your feature request related to a problem? Please describe.

I want to create agents in .NET powered by Google's [Gemini API](https://ai.google.dev/gemini-api) 

### Describe the solution you'd like

An implementation of Autogen.Gemini, like Autogen.OpenAI, I guess?

### Additional context

Are there plans to build this feature?
```[tasklist]
### Tasks
- [x] Add AutoGen.Gemini package #2868
- [x] Add Vertex AI Gemini support #2868
- [x] Add Google AI Gemini support #2868
- [x] Implement GeminiChatAgent #2868
- [x] Add examples for plain text chat, multi-modal chat and function call #2868
- [x] Update website # #2917
```

**Comment by hsm207** [comment]
@LittleLittleCloud Is there a tentative date for when AutoGen.Net 0.0.15 will be released?

**Comment by LittleLittleCloud** [comment]
@hsm207 we ship a new package about every two weeks. You can consume the gemini package from nightly build once it's ready though

**Comment by LittleLittleCloud** [comment]
Currently, there are two ways to consume Gemini model
- Google AI
- Vertex AI

The detailed difference between those two can be found [here](https://medium.com/@martareyessuarez25/what-are-vertex-ai-and-google-ai-studio-the-artificial-intelligence-development-tools-that-already-666bdfe85dbd#:~:text=Difference%20between%20Vertex%20AI%20and%20Google%20AI%20Studio). The main difference are authentication and library support, where `Google AI` uses `api-key` to authenticate the request and doesn't have an official dotnet library while `Vertex AI` use IAM to auth (other authentication methods also support, but using api-key from Google AI is not one of them) and has an official dotnet library `Google.Cloud.AIPlatform.V1`.

To support Gemini in `AutoGen.Net`, we can support consuming from `Vertex AI` first because it seems to be a quick win given that the official library is there. The support for `Google AI` will come later which might require manually crafting a Gemini client from rest api first

**Comment by LittleLittleCloud** [comment]
@hsm207 The `AutoGen.Gemini` is available on nighly build
