### ISSUE TITLE
Multimodal conversable agents

### ISSUE THREAD

**Issue by BeibinLi** [microsoft/autogen#290]
```[tasklist]
### Tasks
- [x] Create a multi-modal agent and test
- [x] Test with GPT4-V API
- [ ] https://github.com/microsoft/autogen/issues/547
```

**Comment by sonichi** [comment]
built by community:
vision: https://www.youtube.com/watch?v=zo2ft4Qje1Y
speech: https://www.youtube.com/watch?v=JgVb8A6OJwM

**Comment by gagb** [comment]
@BeibinLi this issue was marked done and closed but shouldn't that be after multimodal agents become a core part of repo? If this issue was specific to the notebook example, should we have an open issue on the roadmap for multimodal convertible agents?

**Comment by sonichi** [comment]
+1. You can add a task list to keep track of the progress. See #203 as an example.
