### ISSUE TITLE
Roadmap for Profiler for Inter Agent Conversations

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#307]
We want to allow AutoGen developers to analyze the run time performance of multi-agent conversations. 

```[tasklist]
### Roadmap
- [ ] https://github.com/microsoft/autogen/pull/1023
- [ ] Make it easy to profile every agent using garbage collector module
- [ ] Implement a Guidance-based structured labeling utility
- [ ] Add auto-state discovery
```

**Comment by rysweet** [comment]
@gagb - please review. are these still valid for 0.4? will you be continuing these in 0.2? if not please close.

**Comment by rysweet** [comment]
closing as stale, please reopen if you disagree @gagb
