### ISSUE TITLE
[Roadmap]: Enhanced RAG Support

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#3119]
### Describe the issue

One major milestone in release v0.2.33 will be enhanced RAG support. 

### Plan for the next release:

```[tasklist]
### VectorDB integrations
- [ ] GraphRAG support
- [x] [MongoDB](https://github.com/microsoft/autogen/pull/3000)
- [x] [Qdrant](https://github.com/microsoft/autogen/pull/3035)
- [x] Qdrant notebook: https://github.com/microsoft/autogen/pull/3140
```

**Comment by qingyun-wu** [comment]
@thinkall  @randombet let's add RAG-related PRs targeted to be merged in the next release

**Comment by qingyun-wu** [comment]
- For GraphRAG, we are considering integrating[FalkorDB](https://github.com/FalkorDB/FalkorDB) and [MS GraphRAG](https://github.com/microsoft/graphrag) based on current requests from users. Please feel free to share your comments or use cases!

**Comment by thinkall** [comment]
Use #1657 for the solo roadmap for RAG.
