### ISSUE TITLE
[Roadmap]: Google Integrations  

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#3147]
### Describe the issue

```[tasklist]
### Google related integrations
- [x] [VertexAI](https://github.com/microsoft/autogen/pull/3086)
- [ ] [Google search](https://github.com/microsoft/autogen/pull/3049)
- [ ] [Gemini safety setting](https://github.com/microsoft/autogen/pull/3026)
- [ ] https://github.com/microsoft/autogen/pull/3007
- [ ] https://github.com/microsoft/autogen/pull/3207
```

**Comment by jackgerrits** [comment]
Closing in favor of more specific issues, for example https://github.com/microsoft/autogen/issues/3741
