### ISSUE TITLE
[Roadmap]: Improved 'name' support for non-OpenAI clients

### ISSUE THREAD

**Issue by marklysze** [microsoft/autogen#3333]
With the increasing number of new client classes for non-OpenAI inference (Anthropic, Mistral, Cohere, Groq, Together.AI, etc.) we need to continue to cater for these throughout the framework. All these client classes remove the `name` field for inference and this can have an affect on group chats or any interaction that refers to their 'name'.

Listed PRs can help rectify or overcome this issue.

I'll also add the Ollama and Amazon Bedrock client class PRs as optional, as it would be good to have them but the aren't critical to solve the issue in the roadmap. Mistral have updated their client and there's a PR to update our client class to support it.

If you have others, please feel free to add them.

Aiming for next release, 0.2.35

```[tasklist]
### Better `name` support and general non-OpenAI support
- [x] [Add MessageTransforms to GroupChat's select speaker](https://github.com/microsoft/autogen/pull/2719)
- [x] [Include agent's name in content](https://github.com/microsoft/autogen/pull/3334)
- [x] [Ensure name on initial message](https://github.com/microsoft/autogen/pull/2635)
- [ ] [Ollama Client](https://github.com/microsoft/autogen/pull/3056) (optional)
- [x] [Amazon Bedrock Client](https://github.com/microsoft/autogen/pull/3232) (optional)
- [x] [Mistral Client update for v1 support](https://github.com/microsoft/autogen/pull/3356) (optional)
```

**Comment by marklysze** [comment]
cc @sonichi, @qingyun-wu, @skzhang1, @Hk669 - thanks for your help on this everyone!

**Comment by marklysze** [comment]
Thanks @thinkall, @yiranwu0, @Hk669 for your help in getting this done! :fireworks:
