### ISSUE TITLE
Migrate modules with 3rd party dependencies to `autogen-ext`

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#3627]
Some modules need to be migrated to `autogen-ext`:

```[tasklist]
### Tasks
- [ ] [models](https://github.com/microsoft/autogen/blob/staging/python/packages/autogen-core/src/autogen_core/components/models/_openai_client.py)
- [x] Local cmdline code exec
- [x] Docker cmdline code exec
- [x] Azure code executor
```

Additionally, `autogen-ext` should be setup to use extras to manage these dependencies

**Comment by ekzhu** [comment]
Done. Remaining one tracked by #3740
