### ISSUE TITLE
Integrate opensource LLMs into autogen

### ISSUE THREAD

**Issue by LeoLjl** [microsoft/autogen#46]
Currently, autogen.oai only supports OpenAI models. I am planning to integrate open source LLMs into autogen. This would require Hugging Face transformers library.

Some of the open source LLMs I have in mind include LLaMa, Alpaca, Falcon, Vicuna, WizardLM, Starcoder, Guanaco. Most of their inference codes are integrated into Hugging Face transformers library, which can be unified into something like this.

``` python
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "<name-of-model>"

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.bfloat16)
inputs = tokenizer("The world is", return_tensors="pt")
sample = model.generate(**inputs, max_length=128)
print(tokenizer.decode(sample[0]))
```
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/FLAML/issues/1017
- [ ] https://github.com/microsoft/FLAML/issues/1037
- [ ] https://github.com/microsoft/autogen/issues/15
```

**Comment by yhyu13** [comment]
@LeoLjl There are projects like textgen webui that allows openai api adapter to local llms.
And there are proejcts like one-api that servers as middleware for a lot of different remote llm backends

All of them simply redirect the openai api without introducing new code or modifying code

**Comment by LeoLjl** [comment]
Hi @yhyu13, thanks for the valuable information. This is really helpful. I will include it in the next docs update!

**Comment by LeoLjl** [comment]
Hi @ishaan-jaff, liteLLM looks like just the solution we need. I will try it out and include it in the new docs update!

**Comment by YaswanthDasamandam** [comment]
Hi , 
can someone answer my question #89 . 
I am overriding the create class to generate the answers .

**Comment by TheCompAce** [comment]
Well got LiteLLM working, (I added the line to use Swagger for the API setup so it works, but not getting it to work in AutoGen)

`--------------------------------------------------------------------------------
[autogen.oai.completion: 10-03 13:15:41] {223} INFO - retrying in 10 seconds...
Traceback (most recent call last):
  File "F:\My Programs\Auto-Gen\AutoGen\env\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    data = json.loads(rbody)
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\My Programs\Auto-Gen\AutoGen\env\lib\site-packages\autogen\oai\completion.py", line 209, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
  File "F:\My Programs\Auto-Gen\AutoGen\env\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "F:\My Programs\Auto-Gen\AutoGen\env\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "F:\My Programs\Auto-Gen\AutoGen\env\lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "F:\My Programs\Auto-Gen\AutoGen\env\lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "F:\My Programs\Auto-Gen\AutoGen\env\lib\site-packages\openai\api_requestor.py", line 767, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 404 from API (<!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>`

**Comment by ishaan-jaff** [comment]
@TheCompAce I can help you on our discord: https://discord.com/invite/wuPM9dRgDw

**Comment by TheCompAce** [comment]
> @TheCompAce I can help you on our discord: https://discord.com/invite/wuPM9dRgDw

I was a idiot to fix it I had to set the api route to "/chat/completions" to match openAIs, so I used `from flask import Flask, request, jsonify
from flask_swagger_ui import get_swaggerui_blueprint
from litellm import completion

app = Flask(__name__)

# Swagger UI setup
SWAGGER_URL = '/swagger'
API_URL = '/static/swagger.json'
swaggerui_blueprint = get_swaggerui_blueprint(
    SWAGGER_URL,
    API_URL,
    config={
        'app_name': "Litellm Server"
    }
)
app.register_blueprint(swaggerui_blueprint, url_prefix=SWAGGER_URL)

@app.route('/chat/completions', methods=['POST'])
def complete():
    data = request.json
    model = "huggingface/mistralai/Mistral-7B-Instruct-v0.1"
    messages = data.get('messages', [])
    
    response = completion(model=model, messages=messages, max_tokens=8192)
    return jsonify(response)

if __name__ == '__main__':
    app.run(debug=True)
` 
And now I can use the config for AutoGen `[
    {
        "model": "custom_liteLLM",
        "api_base": "http://127.0.0.1:5000"
    }
]`

**Comment by ishaan-jaff** [comment]
made a PR to autogen: https://github.com/microsoft/autogen/pull/95 @LeoLjl

**Comment by henrywithu** [comment]
This looks quite promising. Do you have any example on it? TBH GPT-4 token is pricey, and Code Llama can be a nice choice

**Comment by TheCompAce** [comment]
I have good to get it working above, but seemed to work at first, then started getting token of the limit errors. So maybe I can work on it some more another time.

**Comment by fxtoofaan** [comment]
can you please see if this api integration will work with TheBloke models if possible like this one TheBloke/Mistral-7B-OpenOrca-GPTQ

https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-GPTQ

maybe FastChat+vLLM server in the backend with openai api
serving TheBloke/Mistral-7B-OpenOrca-GPTQ model
any prompt adjustments if needed like chatml etc. 

and example of python code to show how to connect to this using autogen in python script.

**Comment by LeoLjl** [comment]
Hi @fxtoofaan, I think this will solve your question. https://microsoft.github.io/autogen/blog/2023/07/14/Local-LLMs and https://github.com/microsoft/autogen/blob/osllm/notebook/open_source_language_model_example.ipynb

**Comment by bigsk1** [comment]
> @LeoLjl thank you. can you look into these various prompt tempalates: https://github.com/oobabooga/text-generation-webui/tree/main/instruction-templates
> 
> Because of the OpenOrca models I am interested in this prompt template: https://github.com/oobabooga/text-generation-webui/blob/main/instruction-templates/MPT-Chat.yaml
> 
> can this type or prompt template be used in autogen? example of this in python script would be useful. thank you,
> 
> by the way, the model I am playing around with now is this: https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-AWQ

I was able to get oobabooga openai api working last night but was getting token limit errors 2048 and still need to troubleshoot. Was running text gen webui locally and running autogen locally on wsl2. Running oobaba with openai api flag and in a notebook using 

```bash
import autogen

config_list = [
    {
        "model": "gpt-4",
        "api_key": "sk-111111111111111111111111111111111111111111111111",
        "api_base": "http://192.168.XX.XX:5001/v1/chat/completions",
    },
]
```
using model TheBloke_Llama-2-13B-chat-GPTQ. 

Was working just fine and worked just like a open ai api call using gpt4

**Comment by apoorv28goel** [comment]
> > @LeoLjl thank you. can you look into these various prompt tempalates: https://github.com/oobabooga/text-generation-webui/tree/main/instruction-templates
> > Because of the OpenOrca models I am interested in this prompt template: https://github.com/oobabooga/text-generation-webui/blob/main/instruction-templates/MPT-Chat.yaml
> > can this type or prompt template be used in autogen? example of this in python script would be useful. thank you,
> > by the way, the model I am playing around with now is this: https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-AWQ
> 
> I was able to get oobabooga openai api working last night but was getting token limit errors 2048 and still need to troubleshoot. Was running text gen webui locally and running autogen locally on wsl2. Running oobaba with openai api flag and in a notebook using
> 
> ```shell
> import autogen
> 
> config_list = [
>     {
>         "model": "gpt-4",
>         "api_key": "sk-111111111111111111111111111111111111111111111111",
>         "api_base": "http://192.168.XX.XX:5001/v1/chat/completions",
>     },
> ]
> ```
> 
> using model TheBloke_Llama-2-13B-chat-GPTQ.
> 
> Was working just fine and worked just like a open ai api call using gpt4

How is the performance ? can you share some examples ?

**Comment by bigsk1** [comment]
> How is the performance ? can you share some examples ?

good, I'm on a 4090, below is a example to check if working

```bash
import requests
import json

# Define the API endpoint and headers
api_base = "http://192.168.1.68:5001/v1"
api_endpoint = f"{api_base}/chat/completions"
headers = {
    "Authorization": "Bearer sk-111111111111111111111111111111111111111111111111", # Dummy key, replace if your oobabooga instance requires a specific key
    "Content-Type": "application/json"
}

# Define the payload (data to send)
payload = {
    "model": "TheBloke_EverythingLM-13B-16K-GPTQ",  # Replace with your specific model name if different
    "messages": [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2021?"},
        {"role": "assistant", "content": "The Atlanta Braves won the World Series in 2021."},
        {"role": "user", "content": "Where was it played?"}
    ]
}

try:
    # Make the API call
    response = requests.post(api_endpoint, headers=headers, json=payload, timeout=20)

    # Check the response
    if response.status_code == 200:
        print("API call successful.")
        print("Response:", json.dumps(response.json(), indent=4))
    else:
        print(f"API call failed. Status code: {response.status_code}")
        print("Error message:", response.text)

except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")
	
```

```bash
API call successful.
Response: {
    "id": "chatcmpl-1696808596275027712",
    "object": "chat.completions",
    "created": 1696808596,
    "model": "TheBloke_EverythingLM-13B-16K-GPTQ",
    "choices": [
        {
            "index": 0,
            "finish_reason": "stop",
            "message": {
                "role": "assistant",
                "content": "It was played at various locations throughout the United States, including Houston, Texas.\n"
            }
        }
    ],
    "usage": {
        "prompt_tokens": 91,
        "completion_tokens": 18,
        "total_tokens": 109
    }
}
```
in cli you see Output generated in 4.02 seconds (4.73 tokens/s, 19 tokens, context 91, seed 1022663743)
192.168.1.68 - - [08/Oct/2023 16:43:20] "POST /v1/chat/completions HTTP/1.1" 200 -

start oobab with flags --api --listen --extensions openai

**Comment by TheAnachronism** [comment]
When using OpenAI's models, one can easily provide a weblink to a paper, for example, and the models can access that. I guess that is handled on OpenAI's side, as trying this out with local LLMs, this completely fails.
Is there a version of this for local LLMs, or does this have to be built yet?

**Comment by sonichi** [comment]
For new web link that's not in the training data of the OpenAI model, the agent needs to write code to visit the link. Check this example: https://github.com/microsoft/autogen/blob/main/notebook/agentchat_web_info.ipynb

**Comment by babycommando** [comment]
wrote a medium article for doing this with oobabooga.

https://babycmd.medium.com/local-llms-and-autogen-an-uprising-of-local-powered-agents-d472f2c3d0e3

**Comment by Squallpka1** [comment]
Hoping this can integrate with LM Studio because using that is quite easy for beginner. Really easy to just download the LLM, and start the server for local call. Tried the 'https://huggingface.co/spaces/LinkSoul/AutoAgents' and hopping I can just insert the local server URL come from LM Studio and good to go.

**Comment by bomsn** [comment]
I was able to make it work with Google's Vertex AI ( bard, chat-bison..etc  ) by creating a FastAPI endpoint that matches OpenAI **/chat/completions/** endpoint and takes the same data: 

```python
chat = APIRouter(prefix="/vertexai/chat", tags=['Vertex AI Chat'])

@chat.post("/completions/", response_model=ResponseData, summary="Send a chat message to Vertex AI LLM and get a response.")
async def chat_completions_endpoint(request: RequestData, api_key: str = Depends(get_api_key)):
    """
    This function `chat_completions_endpoint` is an API endpoint that accepts POST requests at "/chat/completions/".
    It takes in a JSON request body and an API key from the Authorization header. The JSON request body should contain the following fields:
    - `model`: The name of the Vertex AI model to use for generating chat completions ( only "codechat-bison" and "chat-bison" are supported ).
    - `credentials`: The service account credentials for accessing Vertex AI.
    - `location`: The location of the Vertex AI service (default is 'us-central1').
    - `messages`: A list of chat messages. Each message is a dictionary with 'role' and 'content' fields.
    - `temperature`: The randomness of the generated responses (default is 0).
    - `max_tokens`: The maximum number of tokens in the generated response (default is 2048).

    The function sends a chat message to Vertex AI using the specified model and returns a JSON response containing the generated chat completion.
    The response includes the following fields:
    - `id`: A random ID for the chat completion.
    - `object`: The type of the object, which is "chat.completion".
    - `created`: The timestamp when the chat completion was created.
    - `model`: The name of the Vertex AI model used.
    - `choices`: A list containing the generated chat completion. Each choice is a dictionary with 'index', 'message', and 'finish_reason' fields.
    - `usage`: A dictionary containing the number of tokens used in the prompt, completion, and total.

    If the API key is invalid, the function raises an HTTP 403 error. If any other error occurs during request processing, it raises an HTTP 500 error.
    """
    return 'Match Open AI /chat/completions/ response'
```

In my config file, I just added something like this:
```
    {
        "model": "chat-bison",
        "api_key": "my_api_key",
        "api_base": "http://website-or-localhost/vertexai",
        "location": "us-central1",
        "credentials": "Google cloud service account credentials here"
    }
```

Worked like charm.

**Comment by sonichi** [comment]
Can folks interested in this issue review #831 ? Many thanks.

**Comment by MilutinTokic** [comment]
You guys here are craizy. I tought that I am the only one in the world trying to defeat Open AI ;)

**Comment by bomsn** [comment]
@MilutinTokic , you'll just have to be creative with it. Create an API in the middle that will replicate openAI response format, and use that to connect to any other LLM.

**Comment by ekzhu** [comment]
We are working on local model support: #1345

**Comment by MilutinTokic** [comment]
@bomsn I think that it can be achived with langchain. It can be used with autogen and it can be connected to huggingface

**Comment by bomsn** [comment]
@MilutinTokic yes, that's also an option, but I haven't tried it as I only wanted it to work for a single service without a lot of dependencies. But yeah, that could work.

**Comment by MilutinTokic** [comment]
but that is only way to use AutoGen for free. That is my goal. I mean I am working on a big projects but I dont want to pay to open AI. What are you wonking on? How you use aoutgen? I am into figuring out how to use autogen for free for a few weeks and this is only that I come up with.

**Comment by bomsn** [comment]
@MilutinTokic, to be honest, you'll have to spend money to work with LLM one way or another. You either going to pay OpenAI, Microsoft, Google..etc, or rent a server to run some open source LLM, or run it locally on your computer which will require a decent GPU to get not so good results. If you're trying to get decent results, you'll have to either pay for the existing APIs or, as said, use a very large open source model which will cost you much more money than you'd pay for OpenAI, Microsoft or Google. However, if it's just for learning and it's nothing serious, you can use quantized open source models on hugging face below 7B params on your computer if you have at least 12GB vRam and still, it would be too slow.

**Comment by MilutinTokic** [comment]
@bomsn haha ok I know all that but I acived a lot of things for free so I will this, belive me. I am just starting I know it wouldnt be to fast and to reliable but I dont need it to be I have my methods. I never Paid for any digital/online product that I wanted and I got it eventualy. ;)

**Comment by PyroGenesis** [comment]
Personally, I use FastChat ([as detailed in the AutoGen blog](https://microsoft.github.io/autogen/blog/2023/07/14/Local-LLMs)) but there are a few alternatives mentioned in this thread already like LiteLLM, Langchain, Oobabooga's text-generation-webui. You can even roll your own endpoint with FastAPI as @bomsn mentioned. 

This is until the local model support PR #1345 is merged which would be pretty helpful.

**Comment by Josephrp** [comment]
I've a stack available to test various models for various roles , most require custom code and parameters so i'll be using the custom model client to make tests and notebooks i guess :-)

**Comment by sonichi** [comment]
@PyroGenesis Thanks for the comment. #1345 has been merged. Looking forward to your further feedback.
Thanks @Josephrp for your feedback too.
cc @olgavrou

**Comment by ekzhu** [comment]
Some models don't support tool calls. But have you tried user defined functions? https://microsoft.github.io/autogen/docs/topics/code-execution/user-defined-functions

**Comment by daoxuliu** [comment]
> Some models don't support tool calls. But have you tried user defined functions? https://microsoft.github.io/autogen/docs/topics/code-execution/user-defined-functions

mistral support tool calls. If i use user defined functions,it will cost a lot of token. And a lot of work to change the functions.

**Comment by ekzhu** [comment]
We now support open source and open weight models: https://microsoft.github.io/autogen/docs/topics/non-openai-models/about-using-nonopenai-models
