### ISSUE TITLE
Type errors. So many of them.

### ISSUE THREAD

**Issue by s-cerevisiae** [microsoft/autogen#513]
During my exploration of the library, I found that many of the type annotations are incorrect. It greatly impacts the experience of the library.

So I dove into the code base, following hundreds of the `reportGeneralTypeIssues` diags, and bumped into some actual bugs that affects the library even if the type annotation is totally ignored.

Let me list some of the type errors in `ConversableAgent`:
- `.(a_)send` returns `None` while it claims to return `bool`.
- `.register_reply` have an `Optional` position parameter while `None` is not handled
- `.last_message` should be `Optional` since it can return `None`
- `._print_received_message` doesn't handle a `str` message. **A `self._message_to_dict` conversion is missing here**
- `.check_termination_and_human_reply`'s `sender` **defaults to `None` while nothing handles the `None` case**. Same type of problem also exists in `groupchat.py`.
- `Agent.receive` doesn't even accept keyword arguments while `ConversableAgent.receive` does, but `ConversableAgent` tries to pass `silent` to `receiver: Agent`.

The most horrible one is probably `Completion._get_response`. As far as I understand this function can return `Literal[-1]` while none of the call site handles this case.

These problems are immediately obvious when I run pyright on it.

Please consider fixing those incorrect type annotations and possibly enabling type checking in your development workflow.

PS: Sorry for not proposing this as a PR; I think some of the type errors are related to design decisions (like the `-> bool` one) and I don't know what is intended to be there.
```[tasklist]
### Tasks
- [x] .(a_)send
- [x] .register_reply
- [ ] .last_message
- [x] ._print_received_message
- [ ] .check_termination_and_human_reply
- [ ] Agent.receive
- [ ] `content`, `system_message`, and `messages` @BeibinLi
```

**Comment by swappybizz** [comment]
I believe it greatly hinders my work flow as well

**Comment by BeibinLi** [comment]
@s-cerevisiae  Thanks for raising the issues and working on the type annotations! The changes made in the #572 PR look great. I created a task list within this issue. 

Let me know if you find some other type inconsistencies in the code.
