### ISSUE TITLE
Meta-issue: Testbed loose ends

### ISSUE THREAD

**Issue by afourney** [microsoft/autogen#590]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/autogen/issues/592
- [ ] We need a way of re-running failed scenarios in the testbed (other than manually deleting their results folders)
- [ ] Testbed scenarios need to be updated to cover GPT-4-1106 (turbo)
- [ ] https://github.com/microsoft/autogen/issues/673
- [ ] Add Testbed metrics for common errors (failure to terminate, failure detect code block, etc.)
- [ ] https://github.com/microsoft/autogen/issues/662
```

**Comment by afourney** [comment]
Superseded by #973
