### ISSUE TITLE
rename seed to cache_seed

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#599]
openai introduces a new param in chat completion api:
- seed: This feature is in Beta. If specified, our system will make a best effort to
              sample deterministically, such that repeated requests with the same seed and
              parameters should return the same result. Determinism is not guaranteed, and you
              should refer to the system_fingerprint response parameter to monitor changes
              in the backend.

"Determinism is not guaranteed" - that's a reason to keep the seed in autogen, but rename it to `cache_seed`. Then, we'll be able to support both openai seed and autogen seed.

```[tasklist]
### Tasks
- [ ] seed -> cache_seed in code + doc
- [ ] add this change to migration guide
- [ ] seed -> cache_seed in notebooks & blogposts for retrieve chat, teachable agent, mathchat
```

**Comment by ekzhu** [comment]
Yes.

**Comment by sonichi** [comment]
mathchat still depends on the old version of pyautogen. @kevin666aa may need to decide what to do with it.

**Comment by kevin666aa** [comment]
> mathchat still depends on the old version of pyautogen. @kevin666aa may need to decide what to do with it.

Got it. I will go over MathChat and propose a solution later this week.
