### ISSUE TITLE
Support openai assistant api

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#602]
## Why is this needed?

OpenAI Assistants are out and we should integrate them in AutoGen ASAP!

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/autogen/pull/616
- [ ] https://github.com/microsoft/autogen/pull/632
- [ ] https://github.com/microsoft/autogen/pull/636
- [ ] https://github.com/microsoft/autogen/issues/642
- [ ] https://github.com/microsoft/autogen/issues/643
- [ ] https://github.com/microsoft/autogen/issues/637
- [x] Add groupchat notebook for gptassistant
- [x] add links to all the notebooks in the website and add link to blogpost in readme
- [x] add the test to contrib openai test
- [ ] https://github.com/microsoft/autogen/issues/641
- [ ] https://github.com/microsoft/autogen/issues/686
- [ ] https://github.com/microsoft/autogen/pull/665
- [ ] https://github.com/microsoft/autogen/pull/718
- [ ] https://github.com/microsoft/autogen/issues/916
```

**Comment by DementedWeasel1971** [comment]
Also allow for the use of threads as part of enabling mutli-agent engagement.

**Comment by gagb** [comment]
Relevant issue: https://github.com/microsoft/autogen/pull/616

**Comment by gagb** [comment]
@LeoLjl @qingyun-wu I updated the roadmap with pending tasks.

**Comment by gagb** [comment]
> Also allow for the use of threads as part of enabling mutli-agent engagement.

This was added in #616 and #632. Please let us know if you see issues!

**Comment by mseefelder2** [comment]
@gagb , any estimate on when "Add groupchat notebook for gptassistant" will be availble?

**Comment by gagb** [comment]
> @gagb , any estimate on when "Add groupchat notebook for gptassistant" will be availble?

We already have one? https://github.com/microsoft/autogen/blob/main/notebook/agentchat_oai_assistant_groupchat.ipynb

**Comment by DementedWeasel1971** [comment]
I raised a defect on the same item.  The groupchat is limited to agents that is generated in the session, the groupchat ends up throwing an error if you instantiate an already existing agent.

The bug I logged was https://github.com/microsoft/autogen/issues/1197#issuecomment-1889752818

**Comment by gagb** [comment]
Closing because this roadmap has been accomplished.

**Comment by Phodaie** [comment]
Is there any plans to use AssistantEventHandler? It moves GPTAssistantAgent to the latest OpenAI style by using runs.stream instead of runs.create. Personally I think it's cleaner implementation. It's also needed for future streaming support.

**Comment by Deykeepcomn4me** [comment]
Keep calling from Google accounts these people have stolen money's from me
and are acting as me these are hackers hacking me please contact fbi
