### ISSUE TITLE
Roadmap for AutoGen Evaluation

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#604]
### Considerations
- Differentiate between whether AutoGen is being evaluated or using AutoGen to evaluate something else
- Help decide whether a PR is helpful/breaks something
- Compare value of simpler to complex topologies (e.g, similar to optiguide and group chat)

### Roadmap for AutoGen Evaluation
```[tasklist]
#### Meta Issues
- [ ] Evaluate value of simple vs complex topologies (TOP Priority: when are >2 agents needed?)
- [ ] Shared foundation in the framework on logging, create metrics etc
- [ ] https://github.com/microsoft/autogen/issues/692
- [ ] Develop new AutoGen test suite
- [ ] https://github.com/microsoft/autogen/issues/691
- [ ] Add examples from bubblebench and hugging face dataset into test suite
- [ ] Finalize notebooks and blog post on new metrics
- [ ] Evaluate large multi-modal models
```

**Comment by gagb** [comment]
stale
