### ISSUE TITLE
The "content" param should be flexible: str or List

### ISSUE THREAD

**Issue by BeibinLi** [microsoft/autogen#658]
For instance, the multimodal agents use a list as "content" in messages, but standard GPT-4 and Llama based models are using string.

This basic discrepancy causes issues while two different agents are communicating with each other. An interesting bug is raised by @joshkyh while creating a GroupChat environment with two LMM agents.

```[tasklist]
### Tasks
- [x] Update `ConversableAgent` and all other agents.
- [x] Update `system_message` to be compatible with both str and list
- [x] Update `content` to be compatible with both str and list
- [x] Update `_oai_messages` to be compatible with both str and list
- [x] Check `extract_code`, `function`, and `human_input_mode` accordinly
- [x] Update test cases accordingly.
- [ ] Update notebooks accordingly.
- [ ] update OpenAIWrapper.create()
- [ ] check GptAssistant
- [ ] test Conversable Agent with List content type
```

**Comment by BeibinLi** [comment]
For reference, here is OpenAI's definition of "messages": https://platform.openai.com/docs/api-reference/messages/object
