### ISSUE TITLE
Website Update

### ISSUE THREAD

**Issue by qingyun-wu** [microsoft/autogen#699]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/autogen/issues/687
- [ ] https://github.com/microsoft/autogen/issues/700
- [ ] https://github.com/microsoft/autogen/issues/799
```
