### ISSUE TITLE
[Roadmap] AutoGen Studio

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#737]
> [!TIP]
> ## Want to get involved?
> We'd love it if you did! Please get in contact with the people assigned to this issue, or leave a comment. See general contributing advice [here](https://microsoft.github.io/autogen/docs/Contribute) too.

The app is in `/samples/apps/autogen-studio` .
Contribution guide is [here](https://github.com/microsoft/autogen/tree/autogenstudio/samples/apps/autogen-studio#contribution-guide).

```[tasklist]
### Roadmap
- [x] [P0] Rewrite DB Layer to enable entity linking #1694. #1342
- [ ] [P0] Support for a public gallery of agents, workflows, skills, sessions (logs)
- [x] [P0] Support additional types of workflows in AGS - e.g.., current twoagent/groupchat, sequential chat, automated workflows.
- [ ] [P0] Add ability to learn skills, help users create skills #1442
- [ ] [P0] Better UX for authoring workflows #1362
- [ ] https://github.com/microsoft/autogen/issues/1358
- [ ] https://github.com/microsoft/autogen/issues/3058
- [ ] [P1] Allow users to interrupt a multi-agent conversation
- [ ] [P1] Ability to rate agents, workflows, skills, sessions
- [ ] [P3] Support extracting skills from current session
- [ ] https://github.com/microsoft/autogen/issues/1364
- [ ] [P3] Test UI on mobile device views
- [ ] [P3] Testing on Windows
- [ ] https://github.com/microsoft/autogen/issues/1361
- [ ] https://github.com/microsoft/autogen/issues/1391
- [ ] [AutoGen Studio] Support Authentication in AutoGen Studio
```

**Comment by victordibia** [comment]
Great. Current work for this is being done on the [autogenra](https://github.com/microsoft/autogen/tree/autogenra) branch.

**Comment by iMicknl** [comment]
Would it make sense to have the devcontainer compatible with AutoGen Studio? Currently it is a pain to run AutoGen Studio from the default devcontainer of this project. Best would be if it is fully ready, and even has a VSCode task to start AutoGen Studio.

**Comment by gagb** [comment]
> Would it make sense to have the devcontainer compatible with AutoGen Studio? Currently it is a pain to run AutoGen Studio from the default devcontainer of this project. Best would be if it is fully ready, and even has a VSCode task to start AutoGen Studio.

Good point. Added to the feature list.

**Comment by gagb** [comment]
> > Would it make sense to have the devcontainer compatible with AutoGen Studio? Currently it is a pain to run AutoGen Studio from the default devcontainer of this project. Best would be if it is fully ready, and even has a VSCode task to start AutoGen Studio.
> 
> Good point. Added to the feature list.

@iMicknl this was added

**Comment by glindberg2000** [comment]
Is it possible to use Teachable Agents and if not will it be supported in the future?

**Comment by JonasBE13** [comment]
Will RAG be added for AutoGen studio?

**Comment by romilan24** [comment]
Would it make sense to add Ollama model configuration within the Build -> Models tab?  The only method I know of uses is supported by LiteLLM, e.g. [https://gist.github.com/shimomurakei/5692335e4fdfb12450afa2580002db77](https://gist.github.com/shimomurakei/5692335e4fdfb12450afa2580002db77) but UI configuration would be great.  Thank you!

**Comment by romilan24** [comment]
> Hi @romilan24 ,
> 
> Thanks for the note. Ollama does provide an openai compatible api. https://ollama.com/blog/openai-compatibility. This way, if you put in your model name, base url and api key, (similar to how you will use an openai model) Are you having any issues with this?

That actually worked!  Thank you for the suggestion, very simple implementation.  Then I would suggest we add this as an example for reference because I wasn't able to find any recent examples showing this.

Took some screenshots for reference:
![image](https://github.com/microsoft/autogen/assets/124089036/a57aa719-16e9-43bf-be7a-ab9d4d13cc79)
![image](https://github.com/microsoft/autogen/assets/124089036/285ed604-a7fb-4034-9c04-59171e29e0c1)

Happy to write this up as well.  Thanks @victordibia

**Comment by harrywang** [comment]
@gagb @JingyaChen 

Thanks for creating the great AutoGen framework - I have been using it to teach my students about AI agents. My startup Takin.ai (https://takin.ai/) wants to integrate with AutoGen Studio and see the new interface shown on the release news web page (https://www.microsoft.com/en-us/research/blog/introducing-autogen-studio-a-low-code-interface-for-building-multi-agent-workflows/). 

<img width="1109" alt="Screenshot 2024-07-19 at 7 52 09 AM" src="https://github.com/user-attachments/assets/1632bb3e-63c7-404a-b099-a67d0a785f5c">

It seems the changes are quite significant - I wonder whether you can provide any information on the new version of AutoGen Studio:

1. Will the tech stack be changed? the current one is Fastapi + Gatsby

2. When will the new version be released? Any estimate?

Should we wait for the new version or use the current version?

Thanks a lot for your help!

**Comment by joslat** [comment]
Yes great point, wondering if this roadmap is still relevant. Anyhow I agree on that the UI is sweet enough to "ask for more" :)

**Comment by victordibia** [comment]
@harrywang

We expect the same backend functionality and tech stack, just updates to UX.
- Gatsby and FastAPI will remain unchanged.
- We do not have an ETA at the moment, but working on this.

**Comment by harrywang** [comment]
> @harrywang
> 
> 
> 
> We expect the same backend functionality and tech stack, just updates to UX.
> 
> - Gatsby and FastAPI will remain unchanged.
> 
> - We do not have an ETA at the moment, but working on this.
> 
> 
> 
> 

@victordibia Thanks a lot. Your reply is very helpful!

**Comment by shanmu-raoyunfei** [comment]
When will this new version be released?

![image](https://github.com/user-attachments/assets/6075d7a1-df33-4c21-bdef-53f2c1b73c58)

**Comment by rysweet** [comment]
@victordibia - are you still using this issue for tracking? will these items carry forward to 0.4?

**Comment by dipteshbosedxc** [comment]
When will this new AutoGen Studio UI become available?

**Comment by victordibia** [comment]
@rysweet , we might replace this as work begins replatforming AutoGen Studio on autogen 0.4. 

Hi @dipteshbosedxc , we do not have an ETA at the moment but we are working on it!

**Comment by victordibia** [comment]
AutoGen studio is being re-written to use the updated AutoGen 0.4 api.
As part of that we will be implementing an updated UX (in line with the screenshots above @shanmu-raoyunfei). 
With the new api, a few capabilities are more straighforward to implement (@SailorJoe6) - e.g., being async and message driven we can now more easily stream agent messages, visualize message flow between agents, interrupt runs, implement human input mode (@SailorJoe6) and a few other things.

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/f75b942a-1cbf-4723-a1dc-ea3816928fe1">

https://github.com/user-attachments/assets/dc2b84b0-6302-4f07-b790-e264576bfb1a

Current progress is being tracked in this issue here - #4006 . We will close this issue in favor of that one. 
@SailorJoe6 , and others, thanks for all the contributions on the previous version of AGS, happy to get feedback on the current work.
