### ISSUE TITLE
Support Cost Calculation

### ISSUE THREAD

**Issue by kevin666aa** [microsoft/autogen#770]
```[tasklist]
### Tasks
- [ ] #769 
- [ ] logging history in client.py (TO BE DECIDED)
- [ ] cost & usage summary in client.py
- [ ] cost & usage summary of a single agent.
- [ ] cost & usage summary in groupchat
```

**Comment by sonichi** [comment]
I like the plan. Thanks.

**Comment by rysweet** [comment]
closing as stale, please reopen if you still are working on this.
