### ISSUE TITLE
refactor code-based reply in responsive agent

### ISSUE THREAD

**Issue by sonichi** [microsoft/autogen#8]
Utilize the `config` in `register_auto_reply` to sanitize the implementation of code-based reply.

```[tasklist]
### Tasks
- [ ] In `execute_code_blocks`: Use a passed dict as the config instead of `self._code_execution_config`.
- [ ] When registering `generate_code_execution_reply`, set `config=code_execution_config` parameter.
- [ ] Remove `_code_execution_config` as a variable from ResponsiveAgent.
```

**Comment by thinkall** [comment]
Already supported.
