### ISSUE TITLE
[Meta-issue]: AutoGenBench Work Items

### ISSUE THREAD

**Issue by afourney** [microsoft/autogen#973]
# AutoGenBench Work Items

```[tasklist]
### Small tasks (good first issues)
- [ ] Add a `--dry-run` option
- [ ] https://github.com/microsoft/autogen/issues/1424
```

```[tasklist]
### Immediate Priority
- [ ] https://github.com/microsoft/autogen/issues/1368
```

```[tasklist]
### High Priority
- [ ] Allow users to quickly list and re-run scenarios that failed for non-evaluation-related technical reasons (e.g, Timeout errors)
- [ ] Provide general purpose scripts for computing metrics such as costs, conversation statistics (# messages, etc.), detectable adverse events like loops, etc.
- [ ] Coordinate with AutoGen Studio on logging format and metrics scripts/definitions
- [ ] https://github.com/microsoft/autogen/issues/1054
- [ ] https://github.com/microsoft/autogen/issues/1055
```

```[tasklist]
### Longer Term Priorities
- [ ] Provide the ability to centrally host the *results* of runs/experiments (e.g., a dashboard-like experience for metrics as well as logs/traces)
- [ ] Provide a central location for *running* experiments.
- [ ] Set a cadence for releasing benchmarking products to the AutoGen team (e.g., weekly, prior to dot-releases, prior to major releases, etc)
- [ ] Explore options for running benchmark tasks in parallel
```

```[tasklist]
### Benchmarks to Possibly Onboard
- [ ] MMLU
- [ ] GSM8k
- [ ] WebArena
- [ ] MiniWoB++
```

```[tasklist]
### Wildcard Priorities (Unclear how we should support)
- [ ] Should the Testbed also cover running *other* non-AutoGen agents?
```

### Completed
<details>
  <summary>Click to expand</summary>

```[tasklist]
### Completed tasks
- [ ] https://github.com/microsoft/autogen/issues/1458
- [ ] https://github.com/microsoft/autogen/issues/1461
- [ ] https://github.com/microsoft/autogen/issues/995
- [ ] https://github.com/microsoft/autogen/issues/976
- [x] Write blogpost outlining how to use the Testbed, what benchmarks are currently supported, our roadmap, and how to onboard new ones
- [x] Remove any 3rd-party problem sets from the repo. These should be retrieved and converted via download scripts.
- [ ] https://github.com/microsoft/autogen/issues/985
- [ ] https://github.com/microsoft/autogen/issues/1123
- [ ] https://github.com/microsoft/autogen/issues/987
- [ ] https://github.com/microsoft/autogen/issues/996
```

</details>

**Comment by ph-ausseil** [comment]
@afourney  : 
> Wildcard Priorities (Unclear how we should support)
>>Should the Testbed also cover running other Non-AutoGen agents?

Definitely, there is probably much more to learn that way but it ay also be the only part of the project that survives years. Agents will be replaced by better agent and so on... Ah on the "how", release an API & specs or adopt [market ones](https://github.com/AI-Engineer-Foundation/agent-protocol)

Btw : You might be interested by Hugging Face GAIA

**Comment by afourney** [comment]
Will post an updated roadmap in the future.
